### PR TITLE
Video Sync Prototype 

### PR DESCRIPTION
**Pull request by CobenaA**
Screenshot 2020-06-29 at 4 45 32 PM - Display 1

### CODE REVIEW

**Comment by Sunlis** [comment]
> Why are there two copies of the HTML and javascript?

It's an output/build directory. Someone should probably add a rule to ignore that directory in `.gitignore`

**Comment by Sunlis** [comment]
Filed #18 for the gitignore issue

**Comment by Sunlis** [comment]
You'll have to clear tracking on the `target` directory, since git is already watching it. `git rm -r --cached <folder>`
This won't remove the directory, but it will tell git to stop tracking that directory.

**Comment by CobenaA** [comment]
@googlebot I fixed it.

**Comment by CobenaA** [comment]
@googlebot I consent.

**Comment by glanden** [comment]
@googlebot I consent.

**Pull request merged**
